# fly.toml app configuration file generated for rmx-mdx-24-billowing-darkness-1110 on 2024-01-17T23:08:20-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rmx-mdx-24-staging"
primary_region = "ord"

[build]

[[mounts]]
source = "data"
destination = "/data"
auto_extend_size_threshold = 0

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024
